/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyApp;
import MyLib.Billing;
import MyLib.CornerLot;
import javax.swing.JOptionPane;
import MyLib.Lot;
import MyLib.LotDatabase;
import MyLib.LotService;
import MyLib.LotStatus;
import MyLib.LotDatabaseAdapter;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;


public class BuyLotForm extends javax.swing.JFrame {
    private Lot selectedLot;
    private LotService lotService;
    private String ownerName;
    private String loggedInUser;
    private static final String PURCHASE_FILE = "purchases.txt";
    /**
     * Creates new form BuyLotForm
     */
    public BuyLotForm(Lot selectedLot, LotService lotService,String loggedInUser) {
        Color col = new Color(241, 237, 230);
        getContentPane().setBackground(col);

        initComponents();
        this.selectedLot = selectedLot;
        this.lotService = lotService;
        this.loggedInUser = loggedInUser; 
        displayLotDetails();
        buyButton.setVisible(false);
    }
    
    private void displayLotDetails() {
        DecimalFormat df = new DecimalFormat("#,###");

        String lotType = selectedLot.getLotType().equals("Corner Lot") ? "Corner Lot" : "Regular Lot";
        double finalPrice = selectedLot instanceof CornerLot ? selectedLot.calculateFinalPrice() : selectedLot.getLotPrice();
        int finalSize = selectedLot instanceof CornerLot ? selectedLot.calculateFinalSize() : selectedLot.getLotSize();

        String formattedPrice = "₱" + df.format(finalPrice);

        lotInfoLabel.setText("<html>Block: " + selectedLot.getBlockNumber() +
                             "<br>Lot: " + selectedLot.getLotNumber() +
                             "<br>Size: " + finalSize + " sqm" +
                             "<br>Price: " + formattedPrice +
                             "<br>Type: " + lotType + 
                             "<br>Status: " + selectedLot.getStatus() + "</html>");
    }
    
    private void savePurchaseToFile() {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(PURCHASE_FILE, true))) {
            String lotDetails = selectedLot.getBlockNumber() + "," +
                                selectedLot.getLotNumber() + "," +
                                selectedLot.getLotSize() + "," +
                                selectedLot.getLotPrice() + "," +
                                selectedLot.getStatus() + "," +
                                selectedLot.getLotType();

            writer.write(loggedInUser + "," + lotDetails);
            writer.newLine();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error saving purchase!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        lotDetailsLabel = new javax.swing.JLabel();
        lotInfoLabel = new javax.swing.JLabel();
        buyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        Message = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        purchaseTypeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        purchaseTypeComboBox = new javax.swing.JComboBox<>();
        paymentMethodLabel = new javax.swing.JLabel();
        paymentComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        loanTypeLabel = new javax.swing.JLabel();
        loanTypeComboBox = new javax.swing.JComboBox<>();
        numYearsLabel = new javax.swing.JLabel();
        yearsToPayComboBox = new javax.swing.JComboBox<>();
        monthlyPayment = new javax.swing.JLabel();
        monthlyPayLabel = new javax.swing.JLabel();
        downPayLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        downpaymentFee = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        reservationText = new javax.swing.JLabel();
        reservationfee = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lotDetailsLabel.setText("Lot Details:");
        getContentPane().add(lotDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 74, -1));

        lotInfoLabel.setBackground(new java.awt.Color(235, 227, 219));
        lotInfoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lotInfoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 45, 40)));
        getContentPane().add(lotInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 430, 110));

        buyButton.setBackground(new java.awt.Color(58, 45, 40));
        buyButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buyButton.setForeground(new java.awt.Color(255, 255, 255));
        buyButton.setText("Buy Now");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(buyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        cancelButton.setBackground(new java.awt.Color(58, 45, 40));
        cancelButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, -1, -1));
        getContentPane().add(Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 330, 20));

        jPanel1.setBackground(new java.awt.Color(235, 227, 219));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 45, 40)));

        purchaseTypeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        purchaseTypeLabel.setText("Purchase Method:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Select Purchase and Payment Method");

        purchaseTypeComboBox.setBackground(new java.awt.Color(58, 45, 40));
        purchaseTypeComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        purchaseTypeComboBox.setForeground(new java.awt.Color(255, 255, 255));
        purchaseTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buy", "Reserve" }));
        purchaseTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseTypeComboBoxActionPerformed(evt);
            }
        });

        paymentMethodLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        paymentMethodLabel.setText("Payment Method:");

        paymentComboBox.setBackground(new java.awt.Color(58, 45, 40));
        paymentComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        paymentComboBox.setForeground(new java.awt.Color(255, 255, 255));
        paymentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Loan" }));
        paymentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentComboBoxActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(58, 45, 40));
        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(paymentMethodLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paymentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(purchaseTypeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(purchaseTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchaseTypeLabel)
                    .addComponent(purchaseTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentMethodLabel))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 430, 100));

        jPanel2.setBackground(new java.awt.Color(235, 227, 219));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 45, 40)));
        jPanel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        loanTypeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        loanTypeLabel.setText("Loan Type:");

        loanTypeComboBox.setBackground(new java.awt.Color(58, 45, 40));
        loanTypeComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        loanTypeComboBox.setForeground(new java.awt.Color(255, 255, 255));
        loanTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pag-ibig", "Bank Loan" }));
        loanTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanTypeComboBoxActionPerformed(evt);
            }
        });

        numYearsLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numYearsLabel.setText("# of Years to Pay:");

        yearsToPayComboBox.setBackground(new java.awt.Color(58, 45, 40));
        yearsToPayComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        yearsToPayComboBox.setForeground(new java.awt.Color(255, 255, 255));
        yearsToPayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "5", "10" }));
        yearsToPayComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearsToPayComboBoxActionPerformed(evt);
            }
        });

        monthlyPayment.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        monthlyPayLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        monthlyPayLabel.setText("Monthly Payment (₱):");

        downPayLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        downPayLabel.setText("Downpayment Fee (₱):");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Loan Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(downPayLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(downpaymentFee, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(loanTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loanTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(numYearsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearsToPayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(monthlyPayLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthlyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(downpaymentFee, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loanTypeLabel)
                            .addComponent(loanTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearsToPayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numYearsLabel))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monthlyPayLabel)
                            .addComponent(monthlyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(downPayLabel)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 220, 150));

        jPanel3.setBackground(new java.awt.Color(235, 227, 219));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 45, 40)));

        reservationText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        reservationText.setText("Your reservation fee is (₱):");

        reservationfee.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reservationText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservationfee, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reservationfee, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservationText))
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 260, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void purchaseTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseTypeComboBoxActionPerformed
        // TODO add your handling code here:
    if(purchaseTypeComboBox.getSelectedItem().equals("Reserve")){
        paymentComboBox.setVisible(false);
        buyButton.setVisible(false);

    }
    else if(purchaseTypeComboBox.getSelectedItem().equals("Buy")){
        paymentComboBox.setVisible(true);
                buyButton.setVisible(false);
    }
    }//GEN-LAST:event_purchaseTypeComboBoxActionPerformed

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
       if (selectedLot.getStatus() == LotStatus.AVAILABLE) { 
        if (purchaseTypeComboBox.getSelectedItem().equals("Reserve")) {
            selectedLot.setStatus(LotStatus.RESERVED);
        } else {
            selectedLot.setStatus(LotStatus.SOLD);
        }

        if (selectedLot instanceof CornerLot) {
            selectedLot.setLotSize(selectedLot.calculateFinalSize());
            selectedLot.setLotPrice(selectedLot.calculateFinalPrice()); 
        }

        lotService.updateLot(selectedLot);  
        lotService.saveLotsToFile();  
        
        savePurchaseToFile();

        JOptionPane.showMessageDialog(this, "Transaction successful! Lot is now " + selectedLot.getStatus());

        new ReportForm(lotService, loggedInUser).setVisible(true);
        this.dispose(); 
    } else {
        JOptionPane.showMessageDialog(this, "This lot is no longer available.");
    }  
    }//GEN-LAST:event_buyButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose(); 
    
        MainForm mainForm = new MainForm(); 
        mainForm.setLoggedInUser(loggedInUser); 
        mainForm.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void loanTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanTypeComboBoxActionPerformed

    private void paymentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentComboBoxActionPerformed
        // TODO add your handling code here:
    if(paymentComboBox.getSelectedItem().equals("Cash")){
        buyButton.setVisible(false);

    }
    else if(paymentComboBox.getSelectedItem().equals("Loan")){
        buyButton.setVisible(false);
    }
    }//GEN-LAST:event_paymentComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double finalPrice = selectedLot instanceof CornerLot ? selectedLot.calculateFinalPrice() : selectedLot.getLotPrice();
        int finalSize = selectedLot instanceof CornerLot ? selectedLot.getLotSize() + 300 : selectedLot.getLotSize();
        Billing billingObj = new Billing(ownerName, finalPrice);
        
        if (purchaseTypeComboBox.getSelectedItem().equals("Reserve")) {
            reservationText.setText("Your reservation fee is (₱): ");
            double fee = billingObj.processReservationFee();
            reservationfee.setText(String.valueOf(fee));
            jPanel3.setVisible(true);
            jPanel2.setVisible(false);
            if (!reservationfee.getText().isEmpty()) {
                buyButton.setVisible(true);
            }
        } else if (purchaseTypeComboBox.getSelectedItem().equals("Buy") && paymentComboBox.getSelectedItem().equals("Loan")) {
            jPanel2.setVisible(true);
            jPanel3.setVisible(false);
            if (yearsToPayComboBox.getSelectedItem() == null) {
                return;  
            }
            int years = Integer.parseInt(yearsToPayComboBox.getSelectedItem().toString());
            double processedMonthlyPayment = billingObj.processLoanPayment(years);
            double processedDownPayment = billingObj.processDownPayment(years);
            double roundedValue = Math.round(processedMonthlyPayment * 10.0) / 10.0;
            monthlyPayment.setText(String.valueOf(roundedValue));
            downpaymentFee.setText(String.valueOf(processedDownPayment));
            buyButton.setVisible(true);
        } else if (purchaseTypeComboBox.getSelectedItem().equals("Buy") && paymentComboBox.getSelectedItem().equals("Cash")) {
            jPanel3.setVisible(true);
            buyButton.setVisible(true);
            reservationText.setText("Total Lot Price (₱):");
            reservationfee.setText(String.valueOf(finalPrice));
            jPanel2.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void yearsToPayComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearsToPayComboBoxActionPerformed
        Billing billingObj=new Billing(ownerName,selectedLot.getLotPrice());

        if (yearsToPayComboBox.getSelectedItem() == null) {
            return;  
        }
        int years = Integer.parseInt(yearsToPayComboBox.getSelectedItem().toString());
           double processedMonthlyPayment=billingObj.processLoanPayment(years);
           double processedDownPayment=billingObj.processDownPayment(years);
           double roundedValue = Math.round(processedMonthlyPayment * 10.0) / 10.0;
           monthlyPayment.setText(String.valueOf(roundedValue));
           downpaymentFee.setText(String.valueOf(processedDownPayment));
           
           if(monthlyPayment.getText()!=""){
           }
    }//GEN-LAST:event_yearsToPayComboBoxActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyLotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyLotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyLotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyLotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        LotDatabase lotDatabase = new LotDatabase("lots.txt");  
        LotService lotService = new LotDatabaseAdapter(lotDatabase); 
        Lot selectedLot = lotService.findLot(1, 101);  
        String ownerName = "Name";

        if (selectedLot != null) {
            new BuyLotForm(selectedLot, lotService, ownerName).setVisible(true); 
        } else {
            System.err.println("Error: Lot not found");
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Message;
    private javax.swing.JButton buyButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel downPayLabel;
    private javax.swing.JLabel downpaymentFee;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JComboBox<String> loanTypeComboBox;
    private javax.swing.JLabel loanTypeLabel;
    private javax.swing.JLabel lotDetailsLabel;
    private javax.swing.JLabel lotInfoLabel;
    private javax.swing.JLabel monthlyPayLabel;
    private javax.swing.JLabel monthlyPayment;
    private javax.swing.JLabel numYearsLabel;
    private javax.swing.JComboBox<String> paymentComboBox;
    private javax.swing.JLabel paymentMethodLabel;
    private javax.swing.JComboBox<String> purchaseTypeComboBox;
    private javax.swing.JLabel purchaseTypeLabel;
    private javax.swing.JLabel reservationText;
    private javax.swing.JLabel reservationfee;
    private javax.swing.JComboBox<String> yearsToPayComboBox;
    // End of variables declaration//GEN-END:variables
}
